### ISSUE TITLE
Merge all settings based commands to a single `settings` command.

### ISSUE THREAD

**Issue by Godson777** [Godson777/KekBot#18]
This would lower the command count, but also help generalize all of the settings into a singular command. The user would call `settings wizard` if they wanted a easy-to-use guide on adjusting values for all of their settings. Or for the more advanced users, they could simply call upon arguments based on which setting they want to edit.

This would combine commands like `prefix`, `announce`, and `autorole`, while adding new values to the `settings`.

**Comment by tech6hutch** [comment]
Maybe prefix should stay, though, at least for getting the prefix.

**Comment by Godson777** [comment]
A more detailed version of the previous post:

Port all "settings" based commands (e.g setting prefix, autorole, welcome/farewell messages) into one singular `settings` command. The command allows you to either alias all the different settings (e.g: `settings autorole` to bring up autorole settings), or call `settings wizard` to bring up a system that more or less asks a series of questions and have all your settings done in one go, as it will iterate through all the settings an admin can change. (This may be preferred for users who've just added KekBot, and want the easiest way to change their settings, while more advanced users can rely on manually setting them themselves.)  

However, for simplicity's sake, most settings will have menus built on reactions and such for easier navigation, while others will be changed only slightly to allow for ease of use, and have more documentation where there may have not been any at all. (1.4's current `announce` command is the best example of lack of documentation.)

**Comment by Godson777** [comment]
This was finally implemented in a beta build of 1.5, and will be shipped out in the release version soon.
