### ISSUE TITLE
`skipto` command or an argument for `skip` command?

### ISSUE THREAD

**Issue by Godson777** [Godson777/KekBot#26]
As the title suggests, either a `skipto` command would be used for music players to skip to a certain number in the queue. Alternatively, this could be implemented as an extra argument for `skip`, but, if this route is taken, then this raises a new question: Should the new argument represent which track in the queue to skip to, or the number of tracks to skip?

**Comment by tech6hutch** [comment]
Semantically, I would expect a `skip 2` command to skip two songs instead of one, and a `skipto 2` to skip to the track number "2" in the queue. At least, I think that's what would be most intuitive.

**Comment by Godson777** [comment]
This has been finally implemented in KekBot 1.5.
