### ISSUE TITLE
New layout for music players.

### ISSUE THREAD

**Issue by Godson777** [Godson777/KekBot#27]
Basically, how KekBot shows the major parts of the music player, such as the current playing track, could be redesigned to be in a different format. Instead of pinging the user who queued the track whenever it starts playing, an embed would appear, stating which song just started, and who queued it (without directly sending them a notification).

On top of this, KekBot could also check if the past X messages contain the "now playing" message, and if so, edit that message to reflect the new song playing, instead of sending a new message every time. However, this change would only benefit a music session playing in a channel with low activity, meaning this X value would have to be somewhere around 5 messages. This reduces any unnecessary spam from KekBot, however this also prevents users from seeing which songs have already played (for example, if they were afk while a certain song played, and came back to hear the next one playing).

**Comment by tech6hutch** [comment]
The now playing idea is interesting, but I'm not sure it's worth it tbh.

**Comment by Godson777** [comment]
KekBot 1.4.2 received some minor design changes similar to what was described here. Therefore, this issue is closed.
