### ISSUE TITLE
Error i don't understand

### ISSUE THREAD

**Issue by JohnBoahnerges** [Godson777/KekBot#4]
i get this error when i use commands like $salt and $bork, The  error is, Requires "Living Meme" role!

**Comment by tech6hutch** [comment]
You need to make a role, call it "Living Meme", and assign it to KekBot.

**Comment by Godson777** [comment]
It means exactly that: It needs a role called "Living Meme" (case sensitive). Don't know how? This gif should be helpful, then.

![gif](https://puu.sh/sCFye.gif)
